-- Write SQL queries to perform the following tasks using the Sakila database:
select * from actor
-- List the number of films per category.
SELECT c.name AS category, COUNT(fc.film_id) AS number_of_films
FROM sakila.category c
LEFT JOIN sakila.film_category fc ON c.category_id = fc.category_id
GROUP BY c.name;

-- Retrieve the store ID, city, and country for each store.
SELECT s.store_id, c.city, co.country
from store s
INNER JOIN address a ON s.address_id = a.address_id
JOIN city c on a.city_id = c.city_id
JOIN country co ON c.country_id = co.country_id;

-- Calculate the total revenue generated by each store in dollars.
SELECT store.store_id, SUM(payment.amount) AS total_revenue
from store
join staff on store.store_id = staff.store_id
join payment on staff.staff_id = payment.staff_id
group by store.store_id;

-- Determine the average running time of films for each category.
SELECT category.name, ROUND(avg(film.length),2) AS average_running_time
from category
JOIN film_category ON category.category_id = film_category.category_id
join film on film_category.film_id = film.film_id
group by category.name;
